### ISSUE TITLE
Atributos con guiones

### ISSUE THREAD

**Issue by alu0100699494** [alu0100699494/SCML#10]
Tal como se ha definido la gramática, no se acepta atributos que tengan guiones, al igual que nombres de tags. Por ejemplo, esto no funciona:

```
@head {
  @script data-pepe="lib/pepe";
}

@no-funciona {
 :C
}
```

Que los tags pueda tener guiones es decisión tuya, Sergio; pero al menos los atributos debería poder tenerlos (basta con cambiar las reglas de producción de ID como te convenga).

**Comment by alu0100694987** [comment]
He modificado la expresión regular de ID, para que permita el uso de los guiones, puedes repetir el proceso para TAG si así lo consideras.
