### ISSUE TITLE
Comentarios en SCML

### ISSUE THREAD

**Issue by alu0100699494** [alu0100699494/SCML#11]
¿Usamos para los comentarios los predefinidos por html () dentro de un literal (entre pingüinos) o usamos nuestra propia sintaxis?

**Comment by alu0100700459** [comment]
Detro de un literal seguro que no, porque entonces aparecería en la página. Podemos usar como tú dices los de `<!-- comentario -->` o podemos usar comentarios del tipo de otros lenguajes, como `//comentario` o `/* comentario */`.

A mí personalmente me gusta más la segunda opción, por el hecho de que el lenguaje nuestro se parece a C y sería lógico que también los comentarios fueran iguales. También podemos inventarnos algo, en plan `@@ comentario` para que se parezca a la forma de utilizar tags.

Ahora que lo pienso, lo de `@@ comentario` me gusta cómo queda...

¿Qué piensan?

**Comment by alu0100694987** [comment]
En mi caso preferiría que utilizaramos `//comentario` o `/* comentario */`, para que se parezca a C; aunque tampoco me desagrada la idea de emplear `@@ comentario`.

**Comment by alu0100700459** [comment]
Pues entonces Dani decide:
- [x] `// comentario`
- [x] `/* comentario */`
- [ ] `@@ comentario`

(Nótese la selección múltiple)
