### ISSUE TITLE
Prettyprint del HTML resultante

### ISSUE THREAD

**Issue by alu0100700459** [alu0100699494/SCML#16]
Que el código generado esté indentado, formateado correctamente, etc. para que resulte más sencillo de analizar posteriormente.

**Comment by alu0100699494** [comment]
El código SCML

```
Hola mundo
```

Genera la salida

```
<!DOCTYPE html>
<html>
<body>
Hola mundo</body>
</html>
```

Ese &lt;/body&gt; debería estar en la siguiente línea :+1:

**Comment by alu0100700459** [comment]
Sé por qué pasa, pero es que (si no nos queremos complicar mucho) tenemos que decidir entre

``` html
<!DOCTYPE html>
<html>
<body>
Hola mundo</body>
</html>
```

y cosas como

``` html
<!-- ... -->
<ul>
  <li>
    Texto1
  </li>
  <li>
    Texto2
  </li>
</ul>
```

en lugar de

``` html
<!-- ... -->
<ul>
  <li>Texto1</li>
  <li>Texto2</li>
</ul>
```

que personalmente a mí me gusta más.

De todas formas intentaré mirar eso y de paso formateo bien cuando hay textos multilíneas (en realidad ese es el problema, los textos multilíneas).

Los textos multilíneas son un problema porque para que queden bien hay que invalidar la indentación del usuario y ponerla tú. Normalmente eso está bien, pero no cuando estás en un bloque `<pre>`. Habrá que ver qué hacer en esos casos.

Le echo un vistazo luego a ver qué se me ocurre.

**Comment by alu0100699494** [comment]
Tampoco le des demasiada importancia, era sólo un detalle visual :penguin:

P.D: Molan los iconoes de GitHub :grin:

**Comment by alu0100700459** [comment]
Hay hasta pingüinos... :laughing:

**Comment by alu0100700459** [comment]
Voy a cerrarlo. Si al final decidimos hacer pretty-printing de los textos multilínea lo reabrimos.
