### ISSUE TITLE
Crear nuevo modo de lenguaje para CodeMirror

### ISSUE THREAD

**Issue by alu0100699494** [alu0100699494/SCML#18]
Para que el editor resalte correctamente las palabras de nuestro lenguaje, va a hacer falta crear un parseador sencillo para mostrar la sintaxis. No creo que sea demasiado complicado.

**Comment by alu0100700459** [comment]
Estaría muy bien eso. Yo no sabría hacerlo, pero sí tú puedes...

**Comment by alu0100699494** [comment]
Añadido en e9fc70a9a52b814e215f5bb70a1625a1e565cc19, y queda tal que:

![scml_syntax](https://cloud.githubusercontent.com/assets/5485861/2873469/3cf1ef94-d3ad-11e3-8385-f13ab0e151f0.png)

Si os parece bien, lo dejo así y cierro el issue.

**Comment by alu0100700459** [comment]
Me parece que está muy guapo, pero lo que está fuera de `(")> ... <(")` no es un error. Es decir, en cuanto a los colores está perfecto, pero no es un error en SCML.
Sería un error en el javascript que se genera, claro...

**Comment by alu0100699494** [comment]
Claro, no es un error, sólo lo puse para mostrar que el texto está fuera de un literal.

**Comment by alu0100700459** [comment]
Ah vale... Yo te lo compro.

**Comment by alu0100694987** [comment]
Comprado entonces, me gusta como queda.
