### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by alu0100700459** [alu0100699494/SCML#21]
Estaría bien añadir una base de datos con snippets de código (ejemplos) hechos por nosotros para facilitar el aprendizaje.

Se podrían poner en algún sitio de la interfaz y luego otro sitio donde aparece código escrito por la gente o algo así... No sé, es sólo una idea...
Se podría encargar Cristo de eso, los login y la documentación que haga falta.

Así tendríamos básicamente todo lo que hemos estado haciendo hasta ahora pero mejor.
¿Qué les parece la idea?

**Comment by alu0100694987** [comment]
Sería recomendable. En principio en la página principal debería aparecer un ejemplo sencillo de nuestro lenguaje, y un par de ejemplos más que se puedan cargar y que aparezcan todas las posibilidades que admite scml (similar a lo que hace jison en su página con la calculadora); y que podrían ser fragmentos de prácticas anteriores.
En cuanto a la posibilidad de que guardemos los códigos que escriba la gente, no me convence del todo.

**Comment by alu0100700459** [comment]
Otra idea: Permitir sólo a las personas que hagan login guardar su código pero que sea privado para ellos. Así la página funciona como una IDE más o menos completa. Las personas que no hayan hecho login sólo ven lo que nosotros ponemos y a los que sí les permitimos que borren, renombren y creen su propio código y que puedan volver a acceder a él si hacen login desde algún sitio.

A lo mejor es demasiado complicado, pero quedaría bien, creo...

**Comment by alu0100699494** [comment]
Opino que el objetivo del proyecto y del lenguaje es tener la gramática y la generación de código. Para guardar código, el usuario ya tendrá espacio de sobra en su ordenador, además de otros muchos IDEs online.

Con respecto a los ejemplos, me parece bien tener una serie de ejemplos para que el usuario cargue y vea como es el código generado.

**Comment by alu0100700459** [comment]
Lo digo porque este sería el único IDE de SCML, pero bueno, esto tampoco sería tan importante en todo caso.

**Comment by alu0100699494** [comment]
Se han añadido los ejemplos con un "Combo Box" en ecc7f1566e24408271d6635982a06e1c42ca6f1b
