### ISSUE TITLE
Símbolos especiales y CodeMirror

### ISSUE THREAD

**Issue by alu0100699494** [alu0100699494/SCML#26]
Por suerte (o por desgracia), CodeMirror trata perfectamente los caracteres "<", ">", "&"..., por lo que, para generar el código y mostrarlo en el textarea no hace falta escapar las entidades especiales.

No obstante, si que es necesario escaparlas para mostrar el AST.

Por ejemplo, el código

```
@head { }
Hola Mundo
(")> <div id="pepe"></div> <(")
```

Muestra, en el cuadro del AST, un espacio en blanco correspondiente a la tercera línea de lo anterior.

Debería bastar con realizar un post-procesado del string del árbol para transformar los caracteres especiales, y no realizar el post-procesado para generar el código.

**Comment by alu0100700459** [comment]
Prueba a poner `$('#output').text(JSON.stringify(tree,undefined,2));` en vez de usar el método `html()` [aquí](https://github.com/alu0100699494/SCML/blob/master/public/main.js#L9).

En cuanto a Code-Mirror, lo que creo es que la salida de la generación de texto debería ser tal cual es y debería convertir en todo caso los caracteres escapados a su forma original para ponerlo en la textarea de Code-Mirror, porque lo lógico me parece que el código generado sea html válido.

**Comment by alu0100699494** [comment]
<s>Tanto usando .text() como .html() hacen exactamente lo mismo; vuelcan el contenido tal cual y el explorador lo transforma a HTML.</s> Mostrándolo como texto, las comillas dentro de los tags html se escapan (de " a \" ) en el AST generado. En cuanto a estética, no sabría decir si es algo sin importancia o muy malo.

Por ejemplo, el código SCML

```
(")> <div id="pepe"></div> <(")
```

Produce el AST

```
{
  "type": "document",
  "head": null,
  "body": [
    {
      "type": "text",
      "content": [
        "<div id=\"pepe\"></div>"
      ]
    }
  ]
}
```

**Comment by alu0100700459** [comment]
Las comillas escapadas esas es posible que sean por JSON más que otra cosa... :/
¿Cómo podemos evitar eso? Creo que o hay alguna forma de decírselo a JSON o hay que quitar las "\" de la salida de JSON o algo del estilo...

**Comment by alu0100699494** [comment]
Se puede procesar rápidamente el árbol, reemplazando todas las ocurrencias de \" por ". De todas maneras, da a entender que son unas comillas dentro del valor de un atributo, y no el valor en sí.

**Comment by alu0100700459** [comment]
Es por eso que están, es cosa de JSON, porque si no no se podría parsear... Lo podemos dejar así o modificar la cadena de salida, pero realmente no me parece tan feo... Al menos tiene sentido que estén escapadas.

¿Al final el problema del hueco en blanco se arregló cambiando `html()` por `text()`?

**Comment by alu0100699494** [comment]
Sep, ahora solo falta poner para que la generación de código no cambie los caracteres "<", ">"... por las respectivas entidades HTML.

**Comment by alu0100700459** [comment]
Como te dije antes, creo que es mejor dejar la generación de código tal cual (para que genere HTML válido) y que al meterlo en la textarea se haga la transfomación inversa.
Es el mismo efecto, pero con significado diferente.

**Comment by alu0100699494** [comment]
El no-escapado de caracteres debe hacerse desde el generador de código, y no desde fuera. El problema es que hay que escapar toda entidad HTML que vaya fuera de un literal, y dejar sin escapar lo que vaya dentro.

Por ejemplo, el siguiente SCML

```
@div top {
  (")> <p id="bot"></p> <(")
}
```

Debe traducirse como

```
...
<div id="top">
  <p id="bot">
  </p>
</div>
...
```

Y no como 

```
...
<div id="top">
  &lt;p id="bot"&gt;
  &lt;/p&gt;
</div>
...
```

Ya que los literales también se usaban para poner "raw html". Además, para el caso de javascript, si el usuario pone

```
@script {
(")> if(a > 5) a = 5; <(")
}
```

Se debe traducir como

```
<script>if(a > 5) a = 5;</script>
```

Y no como

```
<script>if(a &lt; 5) a = 5;</script>
```

Creo que ahora si me he explicado un poco mejor.

**Comment by alu0100700459** [comment]
No recordaba lo de "raw html"... Y lo de javascript es verdad, no me había dado cuenta de eso...
Entonces me parece que lo lógico sería simplemente que no se escapara el texto entre `(")> <(")` y sí el resto.

Para eso, claro, habría que modificar la gramática para distinguirlos, pero creo que es la mejor solución al problema.

Resumen:
- text: Se escapan caracteres HTML, como en:

``` html
  <p>3 &lt; 4</p>
```
- raw text: No se escapa nada (copia literal), como en:

``` html
  <script>
    if(a > 5)
      a = 5;
  </script>
```

¿Lo hacemos así? Me parece que evita todos los problemas estos sin tener que hacer una generación de código muy especial ni tener que saber adivinar cuándo hay que escapar cosas y cuándo no.

**Comment by alu0100694987** [comment]
Estoy de acuerdo, y no parece demasiado complicado. Por cierto, ten en cuenta que en el primer caso se tienen que escapar todas las entidades HTML existentes: [Entidades HTML](http://www.w3schools.com/html/html_entities.asp).

**Comment by alu0100700459** [comment]
Sí, claro, antes sólo escapé las básicas porque pensaba permitir por ejemplo escribir el `&` tal cual para que la gente pudiera escribir `&lt;`, que se copiara así mismo en HTML y que en el navegador se mostrara el `<` en vez de `&lt;` si se hubiera escapado el `&` como `&amp;`.

Ahora que vamos a hacer la diferenciación tiene sentido que se escape absolutamente todo en un lado y absolutamente nada en el otro.
