### ISSUE TITLE
Bloques que comienzan con "head"

### ISSUE THREAD

**Issue by alu0100694987** [alu0100699494/SCML#28]
El parser lanza un error cuando  se utiliza como nombre de bloque en el 'body' algo que empieza por "head":

``` java
@header {
  Genero un error :(
}
```

**Comment by alu0100699494** [comment]
Debería bastar con poner un lookahead después de la regla que contiene el '@head' para ver que vengan o blancos "_" o un "{"

**Comment by alu0100694987** [comment]
El problema era otro. No entraba en la regla 'TAG', ya que tenía el lookahead `!("head")`, asi que desde que viera algún nombre que empezara por 'head', ya no casaba.
Sustituí lo anterior por: `!("head"("\\s"/[.;{]))`; es decir, que no encuentre la palabra "head", seguida de "\s", "." (para las clases), ";" (por si no tiene contenido), o "{" (por si tiene contenido).

**Comment by alu0100700459** [comment]
Faltaría el "(", ¿no?. Digo, para que no puedas escribir por ejemplo`@head(atr: "Soy más listo que el parser...);"`

**Comment by alu0100694987** [comment]
Cierto, se me olvidaba, gracias por el aviso.
