### ISSUE TITLE
Bug en los comentarios

### ISSUE THREAD

**Issue by alu0100694987** [alu0100699494/SCML#29]
Al utilizar comentarios después de texto:

``` java
@p {
texto //Comentario salvaje
}
```

No se ignoran, sino que se consideran parte del texto:

``` html
<p>texto //Comentario salvaje</p>
```

**Comment by alu0100700459** [comment]
No hay nadie asignado. ¿Está alguien intentando solucionarlo o es mi trabajo?

**Comment by alu0100699494** [comment]
¿Responde eso a tu pregunta? :smile:

**Comment by alu0100700459** [comment]
:metal::joy: :boom::gun::trollface:

**Comment by alu0100700459** [comment]
Vale, no es tan fácil de solucionar como parecía. Lo que pasa es que si no detecta el texto como espacio vacío (espacios o comentarios) lo mete como literal y aparece como parte del texto después.

El problema es que nosotros dentro de un literal no eliminamos espacios, tabulaciones, etc, por lo que tampoco eliminamos comentarios (son la misma categoría).

Por ejemplo, no tendría sentido convertir esto:

```
@pre {
  Esto       es       un       texto          separado
}
```

en esto:

``` html
<pre>Esto es un texto separado</pre>
```

Y por eso tampoco tendría sentido convertir:

```
@pre {
  Esto /* ¿es? */ un comen // tario
}
```

en:

``` html
<pre>Esto un comen</pre>
```

Resumiendo: Si queremos eliminar comentarios dentro de textos nos vamos a cargar el formato del mismo. Otra solución es diferenciar mejor entre espacio vacío y comentarios, pero es probable que tenga consecuencias.

En realidad no me parece que sea un problema. El comportamiento que tiene es que los comentarios se pueden poner sólo entre otros "bloques" y no dentro de un texto, porque ahí se interpretan como texto.

```
// Primer comentario
@div {
/* multi
 * línea
 */
  Texto
  // No comentario /* Ni esto tampoco */
}

// Otro comentario
@div otro {
  // Comentario
  @p { Contenido }
  // Comentario
  @p { Otro párrafo }
  Texto
  // No comentario
}
```

O eso, o cargarse las cadenas que son comentarios en la generación de código, lo que me parece un poco chapuza porque si no haces la generación de código el árbol sería incorrecto.

Ah, otra cosa que se me ocurre es que como parte de las acciones que se hacen por el parser al encontrar un texto (literal o raw_literal) se eliminen los comentarios antes de meterlos en el resultado (una función javascript de apoyo). A lo mejor así no es tan chapucero y hace lo que queremos... ¿Qué les parece?

**Comment by alu0100699494** [comment]
Se podría hacer una fase de "preprocesado" como hacen los compiladores (como gcc), que básicamente elimine los comentarios de la entrada, ya que no se van a usar para nada al generar el árbol o el código HTML.

**Comment by alu0100700459** [comment]
Ya, pero entonces recorreríamos la entrada 2 veces :/

Sería equivalente a la última opción que dije en cuanto a semántica, así que lo puedo hacer así, que además es bastante sencillo (de hecho se me ocurrió cuando estaba terminando de escribir el comentario...).

**Comment by alu0100699494** [comment]
Parece que podría quedar bien tal como dices, supongo que podría quedar bien.

De todas maneras, no deberíamos eliminar los comentarios en un "raw", puesto que si pone algo como:

```
(")>
<option value="//lolwut">Esto desaparece</option>
<(")
```

Le devolvería

```
<option value="
```

También, el usuario debería poder ser capaz de escribir delimitadores de comentarios de manera que pueda escaparlos, pero supongo que eso ya lo habrás contemplado en la gramática.

**Comment by alu0100700459** [comment]
Sí, los comentarios escapados funcionan bien.

¿Entonces hacemos como lo de escapar entidades HTML? ¿Los comentarios se escapan si están fuera de un `raw_literal` pero no dentro?

**Comment by alu0100699494** [comment]
Yo creo que si, ya que en un <code>raw_literal</code> el usuario debería poder poner de todo menos los delimitadores <code>(")&gt;</code> y <code>&lt;(")</code> (siendo restrictivos).

**Comment by alu0100700459** [comment]
Imagínate...

``` javascript
if (funcion_guay("parametro string(")>12) {
  // nótese el pingüino arriba
  if (12 <(") stringgg".length+1)) {
    // ups...
  }
}
```

**Comment by alu0100699494** [comment]
Te reto a buscar esa secuencia <code>&lt;(")</code> en una práctica que hayamos hecho :smile:

**Comment by alu0100700459** [comment]
Búscala en la versión miniaturizada de jQuery y capaz que la encuentras... :laughing:
(Ya lo probé y no está :cry:)
