### ISSUE TITLE
Barras de desplazamiento en CodeMirror

### ISSUE THREAD

**Issue by alu0100700459** [alu0100699494/SCML#30]
Me he dado cuenta de que como las líneas de código son muy grandes, se quedan cortadas y no hay barra de desplazamiento (hay que ir seleccionando el trozo de texto para mover la vista). ¿Se puede añadir o CodeMirror lo hace demasiado complicado?

Un ejemplo:
![largalarga](https://cloud.githubusercontent.com/assets/5486239/2938972/b3afec3c-d92d-11e3-8807-9729ba960ef1.png)

**Comment by alu0100699494** [comment]
Debe ser solo en FireFox, porque en chrome tengo esto:

![ok](https://cloud.githubusercontent.com/assets/5485861/2938977/1f067262-d92e-11e3-8ceb-28120c6899a8.png)

**Comment by alu0100700459** [comment]
Entonces es cosa de Firefox... Supongo que mejor no meternos a este tipo de problemas.

**Comment by alu0100699494** [comment]
Vaya, tal vez sea cosa de tu versión, porque lo acabo de probar en el de mi PC (FireFox 28.0) y se muestra una barra horizontal cuando hay overflow.

![ok](https://cloud.githubusercontent.com/assets/5485861/2938987/ee255e0a-d92e-11e3-870f-fc6cc0085e12.png)

Después de actualizar a la 29.0.1 (ahora mismo), se sigue mostrando la barra de desplazamiento horizontal.

**Comment by alu0100700459** [comment]
Entonces será cosa de mi navegador sólo. A lo mejor tiene algo que ver con un tema que instalé, así que cerramos esto.
