### ISSUE TITLE
Crear página web

### ISSUE THREAD

**Issue by alu0100694987** [alu0100699494/SCML#9]
- [x] Crear página principal #5
- [x] Crear página de presentación #6

**Comment by alu0100699494** [comment]
Falta por añadir transiciones chulas entre páginas (deslizamientos de izquierda a derecha, etc).

**Comment by alu0100699494** [comment]
Olvidando las transiciones de momento (bastante complejas), faltaría cambiar la gramática de la vista grammar.erb. De momento, se quedará tal cual, y cuando se haya acabado la gramática con jison, actualizaré dicha vista.

**Comment by alu0100700459** [comment]
La gramática está acabada, lo único que falta es un pequeño detalle en la generación de código y al hacer el merge a master se van a cerrar automáticamente todos los issues.
Vamos, que si tienes ganas de escribir la gramática ya se puede hacer porque yo no la voy a cambiar ya.

Cambiando de tema: Las transiciones no sé qué es lo que quieres hacer, pero para algo sencillo si usas jQuery es bastante fácil.
